version: "3.8"

services:
  udp-proxy-api:
    build: .
    container_name: udp-proxy-api
    privileged: true
    ports:
      - "80:8080"
    networks:
      proxy_network:
        ipv4_address: 172.54.1.3
    depends_on:
      - factorio-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  factorio-server:
    image: factoriotools/factorio:stable
    container_name: factorio-server
    restart: unless-stopped
    ports:
      - "27015:27015/tcp"  # RCON
    volumes:
      - /opt/factorio:/factorio
    networks:
      proxy_network:
        ipv4_address: 172.54.1.2

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.54.1.0/24
        